version: '3.8'

services:
  jrtb-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'jrtb_db'
      MYSQL_USER: 'jrtb_db_user'
      MYSQL_PASSWORD: 'dev_jrtb_db_password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - jrtb-db
    env_file:
      - .env